version: "3.7"

volumes:
  rabbitmq-data:
  rabbitmq-log:

networks:
  middleware:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
    - "rabbitmq-data:/var/lib/rabbitmq/"
    - "rabbitmq-log:/var/log/rabbitmq"
    networks:
    - middleware
    env_file:
    - .env

  #rabitmq-slaves:
  #  replicas: 1
  #  image: rabbitmq:3-management-alpine
    #ports:
    #- "5672:5672"
    #- "15672:15672"
  #  volumes:
  #  - "rabbitmq-data:/var/lib/rabbitmq/"
  #  - "rabbitmq-log:/var/log/rabbitmq"
  #  networks:
  #  - middleware
